# Generated by Django 5.2.4 on 2025-07-08 19:49

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Категория")),
                ("description", models.TextField(verbose_name="Описание категория")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Необязательное поле. Родительская категория.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="shop.category",
                        verbose_name="Родительская категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категория",
                "db_table": "db_category",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Товар")),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="Цена товара"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stock_quantity",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="Количество единиц на складе",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        upload_to=shop.models.product_image_path,
                        verbose_name="Фото товара",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="shop.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товар",
                "db_table": "db_product",
                "ordering": ["name"],
            },
        ),
    ]
